#pragma once

#include "cmw/platform.h"
#include "cmw/application.hpp"
#include "cmw/camera.hpp"
#include "cmw/color.hpp"
#include "cmw/error.hpp"
#include "cmw/imgui.hpp"
#include "cmw/input.hpp"
#include "cmw/log.hpp"
#include "cmw/mesh.hpp"
#include "cmw/position.hpp"
#include "cmw/renderer.hpp"
#include "cmw/resource_manager.hpp"
#include "cmw/text.hpp"
#include "cmw/time.hpp"
#include "cmw/utils.hpp"
#include "cmw/window.hpp"

#include "cmw/gl/buffer.hpp"
#include "cmw/gl/object.hpp"
#include "cmw/gl/shader.hpp"
#include "cmw/gl/shader_program.hpp"
#include "cmw/gl/texture.hpp"
#include "cmw/gl/vertex_array.hpp"

#include "cmw/shapes/circle.hpp"
#include "cmw/shapes/line.hpp"
#include "cmw/shapes/point.hpp"
#include "cmw/shapes/rectangle.hpp"
#include "cmw/shapes/triangle.hpp"
